/*
 * CEDE hello_lab (Arduino Uno): USB serial banner + D13 blink + I2C slave @0x43 (Pi→Uno).
 * On serial 'm', runs uno→pico master read of Pico reg0 @0x42 (lab/pi/docs/bus-wiring.md).
 *
 * cede_build_id.h is generated by tools/gen_cede_image_id.sh before arduino-cli compile.
 */
#include "cede_build_id.h"
#include <Wire.h>

static const uint8_t LED_PIN = 13;
static const uint8_t I2C_ADDR_7BIT = 0x43;
static const uint8_t PICO_I2C_ADDR = 0x42;
static const uint8_t REG0_MAGIC = 0xCE;
static const uint8_t REG1_REV = 0x01;

static uint8_t mem[256];
static volatile uint8_t reg_ptr = 0;

static void on_receive(int /*n*/) {
  if (Wire.available() < 1) {
    return;
  }
  reg_ptr = Wire.read();
  while (Wire.available()) {
    mem[reg_ptr] = static_cast<uint8_t>(Wire.read());
    reg_ptr++;
  }
}

static void on_request() {
  Wire.write(mem[reg_ptr]);
  reg_ptr++;
}

static void i2c_slave_begin() {
  Wire.begin(I2C_ADDR_7BIT);
  Wire.onReceive(on_receive);
  Wire.onRequest(on_request);
}

static void run_uno_to_pico_master_probe() {
  Wire.end();
  delay(5);
  Wire.begin();
  Wire.setClock(100000);

  Wire.beginTransmission(PICO_I2C_ADDR);
  Wire.write((uint8_t)0);
  uint8_t txe = Wire.endTransmission(/*sendStop=*/false);

  uint8_t n = 0;
  uint8_t b = 0;
  if (txe == 0) {
    n = Wire.requestFrom(PICO_I2C_ADDR, (uint8_t)1, (uint8_t)1);
    if (n > 0) {
      b = static_cast<uint8_t>(Wire.read());
    }
  }

  Wire.end();
  delay(5);
  i2c_slave_begin();

  if (txe == 0 && n > 0 && b == REG0_MAGIC) {
    Serial.println(F("CEDE i2c uno_to_pico ok"));
  } else {
    Serial.print(F("CEDE i2c uno_to_pico fail tx="));
    Serial.print(txe);
    Serial.print(F(" n="));
    Serial.print(n);
    Serial.print(F(" b=0x"));
    Serial.println(b, HEX);
  }
}

void setup() {
  pinMode(LED_PIN, OUTPUT);

  for (uint16_t i = 0; i < 256; i++) {
    mem[i] = 0;
  }
  mem[0] = REG0_MAGIC;
  mem[1] = REG1_REV;

  i2c_slave_begin();

  Serial.begin(115200);
  delay(1500);
  Serial.print(F("CEDE hello_lab ok digest="));
  Serial.print(CEDE_IMAGE_ID);
  Serial.println(F(" (i2c target 0x43; send m for uno→pico I2C test)"));
}

void loop() {
  while (Serial.available() > 0) {
    int c = Serial.read();
    if (c == 'm' || c == 'M') {
      run_uno_to_pico_master_probe();
    }
  }

  digitalWrite(LED_PIN, HIGH);
  delay(250);
  digitalWrite(LED_PIN, LOW);
  delay(250);

  static uint16_t ms_since_banner = 0;
  ms_since_banner += 500;
  if (ms_since_banner >= 3000) {
    Serial.print(F("CEDE hello_lab ok digest="));
    Serial.print(CEDE_IMAGE_ID);
    Serial.println(F(" (i2c target 0x43; send m for uno→pico I2C test)"));
    ms_since_banner = 0;
  }
}
