/*
 * CEDE hello_lab (Arduino Uno / ATmega328P)
 *
 * USB serial banner + D13 heartbeat LED + I2C slave @0x43.
 *
 * Serial:  Banner prints at startup and repeats every ~5 s as a
 *          heartbeat.  Opening the serial port asserts DTR which
 *          resets the MCU via the ATmega16U2 bridge cap, so the
 *          banner also re-appears on every new connection.
 *          The 5 s interval matches the Pico and is infrequent enough
 *          not to disturb TWI timing.
 *          Send 'm' for a one-shot Uno→Pico I2C master probe.
 *
 * I2C:    Slave at 0x43, register-pointer state machine.
 *          reg0 = 0xCE (magic), reg1 = 0x01 (rev).
 *          Pi validates via: sudo i2cget -y 1 0x43 0 b  → 0xce
 *          Bus uses a TXS0108E level shifter (OE must be tied high).
 *          See lab/pi/docs/bus-wiring.md for the full harness.
 *
 * LED:    Timer1 CTC ISR toggles D13 every ~250 ms — no millis() or
 *          delay() in loop(), leaving it free for serial commands.
 *
 * Build:  cede_build_id.h is generated by tools/gen_cede_image_id.sh
 *          before arduino-cli compile.
 */
#include "cede_build_id.h"
#include <avr/interrupt.h>
#include <avr/io.h>
#include <Wire.h>

/* ---------- constants ---------- */

static const uint8_t LED_PIN        = 13;
static const uint8_t I2C_ADDR_7BIT  = 0x43;
static const uint8_t PEER_I2C_ADDR  = 0x42;   /* Pico on same bus */
static const uint8_t REG0_MAGIC     = 0xCE;
static const uint8_t REG1_REV       = 0x01;

/* ---------- I2C slave ---------- */

static uint8_t mem[256];
static volatile uint8_t mem_address = 0;
static volatile bool mem_address_written = false;

static void on_receive(int /*n*/) {
  if (Wire.available() < 1) {
    mem_address_written = false;
    return;
  }
  mem_address_written = false;
  while (Wire.available()) {
    const uint8_t b = Wire.read();
    if (!mem_address_written) {
      mem_address = b;
      mem_address_written = true;
    } else {
      mem[mem_address] = b;
      mem_address++;
    }
  }
}

static void on_request() {
  if (!mem_address_written) {
    Wire.write(mem[0]);
    return;
  }
  Wire.write(mem[mem_address]);
  mem_address++;
}

static void i2c_slave_init() {
  Wire.begin(I2C_ADDR_7BIT);
  Wire.onReceive(on_receive);
  Wire.onRequest(on_request);
}

/* ---------- LED heartbeat (Timer1 ISR) ---------- */

static void led_timer1_init(void) {
  noInterrupts();
  TCCR1A = 0;
  TCCR1B = 0;
  TCNT1 = 0;
  OCR1A = 3905; /* CTC ~250 ms @ 16 MHz, prescaler 1024 */
  TCCR1B |= (1 << WGM12);
  TCCR1B |= (1 << CS12) | (1 << CS10);
  TIMSK1 |= (1 << OCIE1A);
  interrupts();
}

ISR(TIMER1_COMPA_vect) {
  PINB = (1 << PB5);
}

/* ---------- serial banner ---------- */

static void print_banner() {
  Serial.print(F("CEDE hello_lab ok digest="));
  Serial.print(CEDE_IMAGE_ID);
  Serial.println(F(" (i2c 0x43; send m for peer I2C probe)"));
}

/* ---------- peer I2C master probe (serial 'm') ---------- */

static void run_peer_master_probe() {
  Wire.end();
  delay(25);
  Wire.begin();
  Wire.setClock(100000);

  Wire.beginTransmission(PEER_I2C_ADDR);
  Wire.write((uint8_t)0);
  uint8_t txe = Wire.endTransmission(false);

  uint8_t n = 0;
  uint8_t b = 0;
  if (txe == 0) {
    n = Wire.requestFrom(PEER_I2C_ADDR, (uint8_t)1, (uint8_t)1);
    if (n > 0) {
      b = static_cast<uint8_t>(Wire.read());
    }
  }

  Wire.end();
  delay(25);
  i2c_slave_init();

  if (txe == 0 && n > 0 && b == REG0_MAGIC) {
    Serial.println(F("CEDE i2c peer_probe ok"));
  } else {
    Serial.print(F("CEDE i2c peer_probe fail tx="));
    Serial.print(txe);
    Serial.print(F(" n="));
    Serial.print(n);
    Serial.print(F(" b=0x"));
    Serial.println(b, HEX);
  }
}

/* ---------- setup / loop ---------- */

static uint32_t ms_since_banner = 0;
static uint32_t prev_millis = 0;

void setup() {
  pinMode(LED_PIN, OUTPUT);
  led_timer1_init();

  for (uint16_t i = 0; i < 256; i++) mem[i] = 0;
  mem[0] = REG0_MAGIC;
  mem[1] = REG1_REV;

  i2c_slave_init();

  Serial.begin(115200);
  delay(1500);
  print_banner();
  prev_millis = millis();
}

void loop() {
  uint32_t now = millis();
  ms_since_banner += (now - prev_millis);
  prev_millis = now;

  if (ms_since_banner >= 5000UL) {
    print_banner();
    ms_since_banner = 0;
  }

  while (Serial.available() > 0) {
    int c = Serial.read();
    if (c == 'm' || c == 'M') {
      run_peer_master_probe();
    }
  }
}
