#!/usr/bin/env bash
# Emit cede_gateway_build.h next to main.c (digest embedded in hello_gateway binary).
# Priority: CEDE_IMAGE_ID env, else git rev-parse --short=12 at repo root, else "unknown".
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# HERE = …/lab/pi/native/hello_gateway → repo root is four levels up.
REPO_ROOT="$(cd "${HERE}/../../../.." && pwd)"
OUT="${HERE}/cede_gateway_build.h"

if [[ -n "${CEDE_IMAGE_ID:-}" ]]; then
  id="${CEDE_IMAGE_ID}"
elif id="$(git -C "${REPO_ROOT}" rev-parse --short=12 HEAD 2>/dev/null)"; then
  :
else
  id="unknown"
fi

if [[ ! "${id}" =~ ^[A-Za-z0-9._-]+$ ]]; then
  id="unknown"
fi

cat >"${OUT}" <<EOF
/* Generated by tools/gen_cede_gateway_digest.sh — do not edit. */
#ifndef CEDE_GATEWAY_BUILD_H
#define CEDE_GATEWAY_BUILD_H
#define CEDE_GATEWAY_DIGEST "${id}"
#endif
EOF
echo "==> wrote ${OUT} (CEDE_GATEWAY_DIGEST=${id})" >&2
