/*
 * CEDE hello_lab (Raspberry Pi Pico / RP2040)
 *
 * USB CDC serial banner + LED heartbeat + I2C slave @0x42.
 *
 * Serial:  Banner prints on DTR rising edge (console opened) and
 *          repeats every few seconds while connected.  Unlike the Uno
 *          (where DTR triggers a hardware reset and setup() reprints
 *          the banner), the Pico stays running — periodic re-emission
 *          ensures the validation driver sees the banner even if the
 *          rising-edge print arrives before the expect() starts reading.
 *          tud_cdc_connected() gates all output so the MCU is silent
 *          when no console is attached.
 *          Send 'm' for a one-shot Pico→Uno I2C master probe.
 *
 * I2C:    Slave at 0x42, register-pointer state machine.
 *          reg0 = 0xCE (magic), reg1 = 0x01 (rev).
 *          Pi validates via: sudo i2cget -y 1 0x42 0 b  → 0xce
 *          Bus uses a TXS0108E level shifter (OE must be tied high).
 *          See lab/pi/docs/bus-wiring.md for the full harness.
 *
 * LED:    Blinks the on-board LED at ~2 Hz (250 ms on / 250 ms off).
 *
 * Build:  cede_build_id.h is generated by CMake from CEDE_IMAGE_ID env
 *          or git rev-parse --short=12 HEAD.
 */
#include <stdbool.h>
#include <stdio.h>
#include <string.h>

#include "hardware/gpio.h"
#include "hardware/i2c.h"
#include "pico/binary_info.h"
#include "pico/error.h"
#include "pico/i2c_slave.h"
#include "pico/stdio.h"
#include "pico/stdlib.h"
#include "tusb.h"

#include "cede_build_id.h"

/* ---------- constants ---------- */

#define HELLO_I2C       i2c0
#define I2C_SDA_PIN     0u
#define I2C_SCL_PIN     1u
#define I2C_BAUD_HZ     100000u
#define I2C_ADDR_7BIT   0x42u
#define PEER_I2C_ADDR   0x43u   /* Uno on same bus */

#define REG0_MAGIC      0xCEu
#define REG1_REV        0x01u

/* ---------- I2C slave ---------- */

static struct {
    uint8_t mem[256];
    uint8_t mem_address;
    bool mem_address_written;
} i2c_ctx;

bi_decl(bi_program_description("CEDE hello_lab: USB smoke + I2C target"));

static void i2c_slave_handler(i2c_inst_t *i2c, i2c_slave_event_t event) {
    switch (event) {
    case I2C_SLAVE_RECEIVE:
        if (!i2c_ctx.mem_address_written) {
            i2c_ctx.mem_address = i2c_read_byte_raw(i2c);
            i2c_ctx.mem_address_written = true;
        } else {
            i2c_ctx.mem[i2c_ctx.mem_address] = i2c_read_byte_raw(i2c);
            i2c_ctx.mem_address++;
        }
        break;
    case I2C_SLAVE_REQUEST:
        i2c_write_byte_raw(i2c, i2c_ctx.mem[i2c_ctx.mem_address]);
        i2c_ctx.mem_address++;
        break;
    case I2C_SLAVE_FINISH:
        i2c_ctx.mem_address_written = false;
        break;
    default:
        break;
    }
}

static void i2c_slave_init_all(void) {
    memset(&i2c_ctx, 0, sizeof i2c_ctx);
    i2c_ctx.mem[0] = REG0_MAGIC;
    i2c_ctx.mem[1] = REG1_REV;

    gpio_init(I2C_SDA_PIN);
    gpio_set_function(I2C_SDA_PIN, GPIO_FUNC_I2C);
    gpio_pull_up(I2C_SDA_PIN);

    gpio_init(I2C_SCL_PIN);
    gpio_set_function(I2C_SCL_PIN, GPIO_FUNC_I2C);
    gpio_pull_up(I2C_SCL_PIN);

    i2c_init(HELLO_I2C, I2C_BAUD_HZ);
    i2c_slave_init(HELLO_I2C, I2C_ADDR_7BIT, &i2c_slave_handler);
}

/* ---------- serial banner ---------- */

static void print_banner(void) {
    printf("CEDE hello_lab rp2 ok digest=%s (i2c 0x42; send m for peer I2C probe)\n",
           CEDE_IMAGE_ID);
    fflush(stdout);
}

/* ---------- peer I2C master probe (serial 'm') ---------- */

static void run_peer_master_probe(void) {
    i2c_slave_deinit(HELLO_I2C);
    i2c_deinit(HELLO_I2C);

    i2c_init(HELLO_I2C, I2C_BAUD_HZ);
    gpio_set_function(I2C_SDA_PIN, GPIO_FUNC_I2C);
    gpio_set_function(I2C_SCL_PIN, GPIO_FUNC_I2C);

    uint8_t reg = 0;
    int w = i2c_write_blocking(HELLO_I2C, PEER_I2C_ADDR, &reg, 1, true);
    uint8_t rx = 0;
    int r = -1;
    if (w == 1) {
        r = i2c_read_blocking(HELLO_I2C, PEER_I2C_ADDR, &rx, 1, false);
    }

    i2c_deinit(HELLO_I2C);
    i2c_slave_init_all();

    if (w == 1 && r == 1 && rx == REG0_MAGIC) {
        puts("CEDE i2c peer_probe ok");
    } else {
        printf("CEDE i2c peer_probe fail w=%d r=%d rx=0x%02x\n", w, r, (unsigned)rx);
    }
    fflush(stdout);
}

/* ---------- main ---------- */

int main(void) {
    stdio_init_all();
    i2c_slave_init_all();

    gpio_init(PICO_DEFAULT_LED_PIN);
    gpio_set_dir(PICO_DEFAULT_LED_PIN, GPIO_OUT);

    bool prev_connected = false;
    unsigned ms_since_banner = 0;

    for (;;) {
        bool connected = tud_cdc_connected();

        if (connected && !prev_connected) {
            print_banner();
            ms_since_banner = 0;
        }
        prev_connected = connected;

        if (connected) {
            int ch = getchar_timeout_us(0);
            if (ch != PICO_ERROR_TIMEOUT && (ch == 'm' || ch == 'M')) {
                run_peer_master_probe();
            }

            ms_since_banner += 500;
            if (ms_since_banner >= 5000) {
                print_banner();
                ms_since_banner = 0;
            }
        }

        gpio_put(PICO_DEFAULT_LED_PIN, 1);
        sleep_ms(250);
        gpio_put(PICO_DEFAULT_LED_PIN, 0);
        sleep_ms(250);
    }
}
