#!/usr/bin/env bash
# Emit cede_build_id.h next to the sketch (Arduino include path).
# Priority: CEDE_IMAGE_ID env, else git rev-parse --short=12 at repo root, else "unknown".
set -euo pipefail
SKETCH_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_ROOT="$(cd "${SKETCH_DIR}/../../.." && pwd)"
OUT="${SKETCH_DIR}/cede_build_id.h"

if [[ -n "${CEDE_IMAGE_ID:-}" ]]; then
  id="${CEDE_IMAGE_ID}"
elif id="$(git -C "${REPO_ROOT}" rev-parse --short=12 HEAD 2>/dev/null)"; then
  :
else
  id="unknown"
fi

# Single-line C string: restrict to safe token characters
if [[ ! "${id}" =~ ^[A-Za-z0-9._-]+$ ]]; then
  id="unknown"
fi

cat >"${OUT}" <<EOF
/* Generated by tools/gen_cede_image_id.sh — do not edit. */
#ifndef CEDE_BUILD_ID_H
#define CEDE_BUILD_ID_H
#define CEDE_IMAGE_ID "${id}"
#endif
EOF
echo "==> wrote ${OUT} (CEDE_IMAGE_ID=${id})" >&2
