#!/usr/bin/env bash
# Generate cede_build_id.h for digest attestation.
# Priority: CEDE_IMAGE_ID env > git short hash > "unknown".
# Self-contained — does not reference cede-labgrid repo paths.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT="${PROJECT_ROOT}/cede_build_id.h"

if [[ -n "${CEDE_IMAGE_ID:-}" ]]; then
  id="${CEDE_IMAGE_ID}"
elif id="$(git -C "${PROJECT_ROOT}" rev-parse --short=12 HEAD 2>/dev/null)"; then
  :
else
  id="unknown"
fi

if [[ ! "${id}" =~ ^[A-Za-z0-9._-]+$ ]]; then
  id="unknown"
fi

cat >"${OUT}" <<EOF
/* Generated by cede/gen_build_id.sh — do not edit. */
#ifndef CEDE_BUILD_ID_H
#define CEDE_BUILD_ID_H
#define CEDE_IMAGE_ID "${id}"
#endif
EOF
echo "==> wrote ${OUT} (CEDE_IMAGE_ID=${id})" >&2
