#!/usr/bin/env bash
# AUTO-GENERATED by pi_bootstrap.py generate-places -- do not edit manually.
# Idempotently creates LabGrid places on the coordinator.
# Usage: LG_COORDINATOR=host:port bash lab/pi/scripts/setup_places.sh
set -euo pipefail

LGC="${LGC:-labgrid-client}"

# Place: cede-pico (exporter: cede-pi)
$LGC -p cede-pico create 2>/dev/null || true
$LGC -p cede-pico add-match "cede-pi/cede-pico-port/*" 2>/dev/null || true
$LGC -p cede-pico set-tags board=pico

# Place: cede-uno (exporter: cede-pi)
$LGC -p cede-uno create 2>/dev/null || true
$LGC -p cede-uno add-match "cede-pi/cede-uno-port/*" 2>/dev/null || true
$LGC -p cede-uno set-tags board=uno

echo "Places configured successfully."
